name: FINS Plugin CI/CD

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: osrf/ros:humble-ros-base

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Basic Tools
        run: |
          apt update
          apt install -y curl git sudo jq ninja-build software-properties-common bc wget

      - name: Cache Fins-SDK
        id: cache-fins-sdk
        uses: actions/cache@v4
        with:
          path: /opt/FineVision
          key: fins-sdk-v2-dev-${{ runner.os }}

      - name: Install Fins-SDK
        if: steps.cache-fins-sdk.outputs.cache-hit != 'true'
        run: |
          cd /opt
          git clone --depth 1 -b "V2(dev)" --recursive --shallow-submodules https://gitee.com/fins-robotics/FineVision

      - name: Install Fins-CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/Han-Yu-Meng/fins-cli/main/install.sh | sudo bash || true
          
          mkdir -p /github/home/.fins
          cp -r /root/.fins/* /github/home/.fins/ || true

      - name: Setup FINS Workspace
        run: |
          mkdir -p /github/home/.fins/logs
          nohup finsd > /github/home/.fins/logs/finsd_boot.log 2>&1 &
          
          sleep 8

          # 4. 注册工作区
          fins workspace add ci_robot
          fins workspace list

      - name: Solve Dependencies
        run: |
          source /opt/ros/humble/setup.bash
          sudo fins dep solve vision

      - name: Build Plugins
        run: |
          source /opt/ros/humble/setup.bash
          fins build --all

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fins-plugins
          path: /github/home/.fins/install/